global:

route:
  receiver: 'telegram-bot'


receivers:
  - name: 'telegram-bot'
    telegram_configs:
      - bot_token_file: /etc/alertmanager/.telegram_token
        chat_id: 93372553
        message: Server is down
